dist: focal
os:
- linux
services:
- docker
language: java
jdk:
  - openjdk8
cache:
  directories:
  - "$HOME/.m2"
before_install:
- sudo apt-get install -qq texlive-latex-base texlive-latex-extra texlive-fonts-recommended lmodern 
  xzdec -y
script:
- echo "$docker_password" | docker login -u "$docker_username" --password-stdin
- mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -f latex/pom.xml -Pcodecoverage,release clean install docker:push
deploy:
  provider: releases
  token:
    secure: JhYKgsXgu74+snLH1XK1ZZknA4X7a8V6AKyiIyZjX7ph3uJ1aIzOaMKsWvrwYkwrB5stE4H+yDmvgPgrzRuRlWTwh+S0ArhbIQDTsezTAX0gCxWIiAEcpK+/1tZmC8JUR4gFPvn+i6VZ0hnbMteV4wj+gox2aFac0LadCkyMTsp1oXmKvp/3xOEdKNhLlgN2J3JCHMu28Zml65ydDaLgtt6seUbZ5tu/Jt1A3YdqrzxTvdqzCdMdis6oj9Zu7/b9BEnEazsJvSVzWx6e4GRvLp9G7KMOOgONbRBsW/kQ3fFVVTgKw3C0v4MpmocOB2rOtsmrgqC1s7Wr25zPim/cMXsSKht46ygOdS0nDfeX6AfRq9c/7ttlhTPQDxBoB+cfoTaxrWMftnFOcluZR6P3yRgZ/GccOCb68/ErvnyQ6Pnfz/Am/8CJLh9Ip49DpSGAZnEaq9ILSceUmA5kvBSrwXCADsa+91jdis8lwZrA29FwaU9s7oFUrcU9QsRx3BIBNv0+bpks/fxz3XnDLqJ8Q7qkNWi2ET9n8GShwX196EU7RYcM06gUMt2/ErIIdCcDBKBAmCOE4LC8EVpIpAxpDSt8vGr2UmsSg7ayU2wL2lfMsdqb3nhwfq+J8R/SCT1mbHKOkpbk1YVaqxqNEQJH+fpYUbLoOv5vcfZ0zHLtRv0=
  file: latex-distribution/target/release.zip
  overwrite: true
  on:
    repo: vsfexperts/LaTeX
    tags: true
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - docker_username=vsfalexanderpilch
  - secure: "vT/614nYcwbOP5tmSkLTCIqjXiXe0k3yj2IBPjP0DcIo6ISXFOMPbpawSDJlk+ZdVYcfp1cVGD8iAIsnoPHsDryTXzVqE3dyCYAc5sW4xgTevMBZU4K/ONfhx0OD76h2IWFD5PT7+fAlu1G9AZnYnIq7ouWwTGeb5JZd0svdvRb7R7omUTFIGeuC1Oi2ZgxtUpyFVoh6g56VKxMEJ8+ur86xvms78UNEVR0FR5XVKJdbxaLrvt9nmD+ZDivHoBAlNojq0vPImRuQBebzlaZ/tYiHDnzEBLaP47swXbK1/I2mceFCS2LWi4+uFdHLLa7YiMooAXX1jpplK5o/ocjFtaymN6sFgkL+sMTuZDv2pnzo9a6ivDMAnxfLMvGdI4YFgQji3xIzHcQUidJsYCqYkLWP8c4sHBa85wIkHiDjNbbMd2/MFrYG9w0aEqz6wbNmq1RfJI2BXs4F3dxq54oHyV91WKUDhaUbR+kYPZF6nugT7mfi+K2QzRUAXqiJ+ArMR9g5g2hoIVeNstDZ7KbaMbCibSdIddXM/f55yQXb4rqwDd7mT4DbnR0pR7AzzVTdSJvti7B60B8utX71+N2+shsr95xfmBpj9W9xyTEzcINGY3IWconR/fQvqhlzRIdkj9HT2Il8KC/L0/F+/7KbUxjdrGLvHNKaJtB3cqPV8Ok="
