sudo: required
services:
- docker
language: java
cache:
  directories:
  - "$HOME/.m2"
before_install:
- sudo apt-get install texlive-latex-base texlive-latex-extra texlive-fonts-recommended
  xzdec -y
script:
- echo "$docker.password" | docker login -u "$docker.username" --password-stdin
- mvn -f latex/pom.xml -Pcodecoverage,release clean install docker:push
deploy:
  provider: releases
  api_key:
    secure: JhYKgsXgu74+snLH1XK1ZZknA4X7a8V6AKyiIyZjX7ph3uJ1aIzOaMKsWvrwYkwrB5stE4H+yDmvgPgrzRuRlWTwh+S0ArhbIQDTsezTAX0gCxWIiAEcpK+/1tZmC8JUR4gFPvn+i6VZ0hnbMteV4wj+gox2aFac0LadCkyMTsp1oXmKvp/3xOEdKNhLlgN2J3JCHMu28Zml65ydDaLgtt6seUbZ5tu/Jt1A3YdqrzxTvdqzCdMdis6oj9Zu7/b9BEnEazsJvSVzWx6e4GRvLp9G7KMOOgONbRBsW/kQ3fFVVTgKw3C0v4MpmocOB2rOtsmrgqC1s7Wr25zPim/cMXsSKht46ygOdS0nDfeX6AfRq9c/7ttlhTPQDxBoB+cfoTaxrWMftnFOcluZR6P3yRgZ/GccOCb68/ErvnyQ6Pnfz/Am/8CJLh9Ip49DpSGAZnEaq9ILSceUmA5kvBSrwXCADsa+91jdis8lwZrA29FwaU9s7oFUrcU9QsRx3BIBNv0+bpks/fxz3XnDLqJ8Q7qkNWi2ET9n8GShwX196EU7RYcM06gUMt2/ErIIdCcDBKBAmCOE4LC8EVpIpAxpDSt8vGr2UmsSg7ayU2wL2lfMsdqb3nhwfq+J8R/SCT1mbHKOkpbk1YVaqxqNEQJH+fpYUbLoOv5vcfZ0zHLtRv0=
  file: latex-distribution/target/release.zip
  skip_cleanup: true
  on:
    repo: vsfexperts/LaTeX
    tags: true
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
    - docker.username=vsfalexanderpilch  
    - secure: mJr8kh14i09QQ2naK2C5alLfB4TmGrT9wGzy5raIkHbc0cwXtsDAGME9x2h5V5NqX4dOkU3OKz0Oyr8T9IwZyvhB9o5rzVT7LL/Pb1MomxKXnwU3UJhpZOLdxu0stp5Z1tFxmwvInkVTGwveTjXEfcrFZjaba0Bb3KJ8fLNG78NGQLH+gQijJJ3kh6JLqwtnWVY1wxh7LyvLqM08AjDwO/7K69mw6pMEiV3kFjThlCbrH/8RfmHMP4IDd0Vx0JDpHiNRj1NJKKEoZKPTl8s3NdWhzS6ZVav1rla2Rtldpa0JNTC/TLQ7M0uYRfxjHoxr7E76gxS0MFHSk9YNisgxB6ZwjqNrUqyQf5zSrs3+X9UvPT5vOjVmGOebiIudX17FeEHTfgE0QVLTo/bQd3rr0mJJTZ5MUygIHrtJwOi2tFOSJTCBmuKHfGdh5uJWGeba0ruASsGHdZFwc6naVE7oT2L9OBPNI6RKdsLUYTTMU6FSe7zceVO5dmt5PyrDg5ilQFsmLOhxSJ036khsbrboQ3wSYy30i277+r+lysYhgodBr6ZAx0IrorbTCSra+TYWJAY6wlKsAyeQNyCLmyPkeJYsFg9hjjJTlK1yMqXQZJoMsWn3xIyEnebABrI7Sr1r2BHpvcK6x/9jMgbeJ6wGOt3+LJHtbTDNIBQ1qg9fFs0=
