sudo: required
services:
- docker
language: java
cache:
  directories:
  - "$HOME/.m2"
before_install:
- sudo apt-get install texlive-latex-base texlive-latex-extra texlive-fonts-recommended
  xzdec -y
script:
- echo "$docker_password" | docker login -u "$docker_username" --password-stdin
- mvn -f latex/pom.xml -Pcodecoverage,release clean install docker:push
deploy:
  provider: releases
  api_key:
    secure: JhYKgsXgu74+snLH1XK1ZZknA4X7a8V6AKyiIyZjX7ph3uJ1aIzOaMKsWvrwYkwrB5stE4H+yDmvgPgrzRuRlWTwh+S0ArhbIQDTsezTAX0gCxWIiAEcpK+/1tZmC8JUR4gFPvn+i6VZ0hnbMteV4wj+gox2aFac0LadCkyMTsp1oXmKvp/3xOEdKNhLlgN2J3JCHMu28Zml65ydDaLgtt6seUbZ5tu/Jt1A3YdqrzxTvdqzCdMdis6oj9Zu7/b9BEnEazsJvSVzWx6e4GRvLp9G7KMOOgONbRBsW/kQ3fFVVTgKw3C0v4MpmocOB2rOtsmrgqC1s7Wr25zPim/cMXsSKht46ygOdS0nDfeX6AfRq9c/7ttlhTPQDxBoB+cfoTaxrWMftnFOcluZR6P3yRgZ/GccOCb68/ErvnyQ6Pnfz/Am/8CJLh9Ip49DpSGAZnEaq9ILSceUmA5kvBSrwXCADsa+91jdis8lwZrA29FwaU9s7oFUrcU9QsRx3BIBNv0+bpks/fxz3XnDLqJ8Q7qkNWi2ET9n8GShwX196EU7RYcM06gUMt2/ErIIdCcDBKBAmCOE4LC8EVpIpAxpDSt8vGr2UmsSg7ayU2wL2lfMsdqb3nhwfq+J8R/SCT1mbHKOkpbk1YVaqxqNEQJH+fpYUbLoOv5vcfZ0zHLtRv0=
  file: latex-distribution/target/release.zip
  skip_cleanup: true
  on:
    repo: vsfexperts/LaTeX
    tags: true
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - docker_username=vsfalexanderpilch
  - secure: Qr286m/BUnsA8qdx67ftDhnKs9t3/gap+H8o9WSKQnxExddF42K+ZjjIaQAXWaIH98AtJhM41gLXNu2DAZZsFSlIV+GYiCFtt3URT44GxeO13iXijPXzN5XQmEij5OzA79heT+xtQ0O8vvPkxWYWIZg3mdVWweZOadmi7W0hlvM8XX2FhNEDLukEvoFcXKFit33FnuCoHebZjQE91zxxzGUqxAAd4EkPg5w/EzNC9AUBMYVzMSOhU6sUFPGqR0sxIpUJ2EI784q/dxo4Yzt8E9r6Uf7lc1izkdLVdGf9TjVpzpawjb1KZuAH0QWKNg3Fbovfidg5822TzC6nogJKSRpqyHOH4IufEiwCVTEWLApgGnRGjXH42LZnMoOQ+PFsSyS+Jmq6ymT8k+kdHOKlBEWzK73qcY3GD02lZQzKklfElaIEPSS9/3RvJMf5y1CVa7jdYc0LY3gSzUODg8p4pJN8RHAIdNzTxADb26ycttGfjwaAdhtAD3gvNbXpq7wXkQtTjBJwNWHuaye7GrO7JqGJBzujNGmdUUjQtX3giYamAod6H04CnRZeWoJVfm0eDkHerxpTyGZuBefvLbzblXG1cl6f+O30AgX0tR1kGQx/xp14yXDAzHsSFa1iBshro2oM9qsNM/z9BiTSWhpMWpn7YbyD+F+NGm92V4OpehE=
