##########################
## Global
##########################
spring.jmx.unique-names: true
management.endpoints.jmx.domain: latex-renderer
management.endpoints.web.exposure.include: "*"
management.metrics.web.server.request.autotime.enabled: false
server.error.whitelabel.enabled: false
server.tomcat.additional-tld-skip-patterns: "*.jar"

--- 

##########################
## Default
##########################
spring.config.activate.on-profile: default 
 
renderer:
  archiveDirectory: c:\temp\archive
  workDirectory: c:\temp
  threads: 1

--- 
##########################
## Prod
##########################
spring.config.activate.on-profile: prod

renderer:
  archiveDirectory: /var/archive
  workDirectory: /tmp/renderer
